version: '2'
services:
    nginx:
        image: nginx
        volumes:
            - ./docker/nginx/etc/:/etc/nginx/conf.d
            - ./:/var/www/html
#        ports:
#            - "8086:80"
        links:
            - fpm
        environment:
            - "VIRTUAL_HOST=agares.info,www.agares.info"
        networks:
            - frontproxy_default
            - default
    
    fpm:
        build: ./docker/php
        volumes:
            - ./:/var/www/html
        environment:
            - AGINFO_ENV=prod
        links:
            - pgsql
    
    pgsql:
        image: postgres
        volumes:
            - ./data/pgsql:/var/lib/postgresql/data/
        environment:
          POSTGRES_USER: "${PGSQL_USER}"
          POSTGRES_PASSWORD: "${PGSQL_PASSWORD}"
          POSTGRES_DB: "${PGSQL_DB}"

networks:
    frontproxy_default:
        external: true
