version: '2'
services:
    nginx:
        image: nginx
        volumes:
            - ./docker/nginx/etc/:/etc/nginx/conf.d
            - ./:/var/www/html
        links:
            - fpm
        environment:
            - "VIRTUAL_HOST=agares.info,www.agares.info"
        restart: always
        networks:
            - frontproxy_default
            - default
    
    fpm:
        build: ./docker/php
        restart: always
        volumes:
            - ./:/var/www/html
        environment:
            - AGINFO_ENV=prod

networks:
    frontproxy_default:
        external: true
