imports:
  - { resource: "config.yml" }

framework:
  router:
    resource: "%kernel.root_dir%/config/routing_dev.yml"
    strict_requirements: false
  profiler: { only_exceptions: false }

web_profiler:
    toolbar:              true
    position:             bottom
    intercept_redirects:  false
    excluded_ajax_paths:  ^/bundles|^/_wdt