imports:
  - { resource: "@AppBundle/Resources/config/services.yml" }
  - { resource: "@BlogBundle/Resources/config/services.yml" }

framework:
  templating:
    engines: ['twig']
  secret: "someveryrandomstuffherethatshouldbeinenv" #fixme