blog_homepage:
    path:     /
    defaults: { _controller: blog.controller.default:indexAction }

blog_post:
    path:     /post/{slug}
    defaults: { _controller: blog.controller.default:postAction }