app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_cv:
    path: /cv
    defaults: { _controller: AppBundle:Cv:index }

app_blog:
    path: /blog
    defaults: { _controller: AppBundle:Blog:index }